### ISSUE TITLE
How to solve shared files/dependencies across different plugins?

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#21]

**Comment by maraf** [comment]
**Option 1**: When installing plugin, take a list of all extracted files.

**Comment by RussKie** [comment]
I think this is a complex problem.
Right now all plugins are compiled together against the same set of dependencies - e.g. they all shared the same version of Json.NET etc.
If plugins are now built at their own cadence, their dependencies will differ from one plugin to another. This means we can't install all plugins under Plugins folder.

I think we may need to adjust where plugins live, e.g. the standard plugins (i.e. those shipped with the official release) will live under _Plugins\official_ (the name can change) and other plugins will live under own named folders (e.g. _Plugins\AppVeyorIntegration_).
We will also need to load each plugin into own AppDomain so we can load all assemblies from each plugin.

/cc: @sharwell @KindDragon @jbialobr @gerhardol @drewnoakes thoughts?

**Comment by drewnoakes** [comment]
Restricting the discussion to assembly/package references for a moment, can we reasonably detect and report such conflicts when scanning for plugins?

Does MEF have anything to say about this?

**Comment by gerhardol** [comment]
How big is the need for handling plugins outside of GE core?
Should we spend time on this?

"Private" plugins can be handled by private builds.

**Comment by RussKie** [comment]
Private builds built separately will introduce assembly version clashes.
This discussion is about how we can mitigate the risk.

**Comment by sharwell** [comment]
Official support for plugins via MEF is non-trivial for development and distribution strategies. I would not recommend pursuing it at this stage unless it became a primary adoption requirement, and even then it would require some long discussions about the impact to overall development.

**Comment by RussKie** [comment]
Are you able to clarify why?
What would be a better/preferred strategy?

**Comment by sharwell** [comment]
@RussKie We would need to strictly control the public API (by making everything internal until it passes API review), and then once something is made public we can't change it's behavior even if we change our mind in the future about how things should work. Then we need to rigorously apply a versioning policy for assembly names and use binding redirection to ensure future source and binary compatibility.

The best strategy is to not support the area at all. It's difficult and time consuming to get right, and anything else will fall on the floor a year or so after you start (if you aren't strict about versioning, it still takes a bit of time to realize how serious the impacts are because most approaches work at least for a short while).

**Comment by gerhardol** [comment]
> Private builds built separately will introduce assembly version clashes.

What I meant is that if someone adds "PluginX", they can include the plugin in their private build of GE including the plugin until it is included in GE. I rather see that the limited GE resources are spent on features that improves GE.

A monolith is in most cases simpler to move forward than a flexible structure.

**Comment by RussKie** [comment]
Sam, I agree with you to a certain extent. However I personally don't see
it as a major deal breaker.

A plugin is designed for a particular version of GE, which provides a
public API for integration.

If we decide to change the public API in the next version and a plugin
fails - the plugin author will need to release a new version compatible
with the new version of GE.

That's how VS is doing it, isn't it?

**Comment by maraf** [comment]
I'm going to close this as there is no related work right now. 
The solution has also been discussed here gitextensions/gitextensions#5776.
