### ISSUE TITLE
Close GitExtensions (all instances) when starting PluginManager

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#22]

**Comment by maraf** [comment]
Added question.
Plugin settings contains option to "always close" GitExtensions.

**Comment by RussKie** [comment]
Personally I'm finding the popup somewhat annoying.
In event when a user wants to simply browse and/or check what plugins are installed, the popup may unnecessarily irritate the user. Perhaps the popup is better placed at the time when the user attempts to install or uninstall a plugin.

**Comment by maraf** [comment]
OK. No problem with this.

**Comment by maraf** [comment]
A message box inside PackageManager just before installing/uninstalling package.
Configuration property remains for auto-closing all instances.
