### ISSUE TITLE
Option for check for updates on startup

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#23]
Extend GitExtensions integration (#19) with option (bool) to check for package updates on startup.
There should also be some limits not to check on every run.

**Comment by RussKie** [comment]
Be careful with a feature creep 🙂
Put it on a backlog, if necessary, but I wouldn't call this a must have.
Occasional check (like weekly or monthly) is sufficient. Even that isn't
necessary for an MVP.

We still don't really know how it would integrate with GE, whether it would
get accepted by the Core team and/or the community, or whether it would be
used at all....

I would hate to see you putting a lot of effort in vain.

**Comment by maraf** [comment]
Yeah, I miss assigned it for 0.2, just wanted to dump an idea.

**Comment by maraf** [comment]
Closed by #81.
