### ISSUE TITLE
Isn't compatible with GE v3

### ISSUE THREAD

**Issue by RussKie** [maraf/GitExtensions.PluginManager#32]
I've installed the plugin manager into GE v3 (the current master version) and it didn't appear under Plugins menu.
I haven't investigated it, I suspect the plugin may be missing MEF `[Export(typeof(IGitPlugin))]` decoration.

**Comment by maraf** [comment]
I will add it, I never tested it against GE repo.
V3 uses "standard" MEF?

**Comment by RussKie** [comment]
Yes, standard MEF, AFAIK.
You can check how other plugins are decorated.

**Comment by RussKie** [comment]
I have dropped it in my debug version of GE following the guide, yet I can't see it in my plugins list.

**Comment by RussKie** [comment]
I have dropped [0.4.0 version](https://github.com/maraf/GitExtensions.PluginManager/releases/download/v0.4.0/GitExtensions.PluginManager-v0.4.0.zip) in my debug version of GE following the guide, yet I can't see it in my plugins list.

**Comment by maraf** [comment]
To be honest, I did't tested it - just added the import.

Now I have found that `GitPluginBase.Execute` has different type of its parameter - changed from `GitUIBaseEventArgs` to `GitUIEventArgs` in v3. 
It works with this change, but it doesn't work in v2.51.

When is v3 going out?

**Comment by maraf** [comment]
We are already using PluginManager at my organization which is why I'm still targeting v2.51.
As current functionality is all we need right now, I think I can move to v3 from next release and drop support for v2.51. This is also a good opportunity to test versioning.

**Comment by maraf** [comment]
Finally, it's working.
Tested against current GE master branch.
