### ISSUE TITLE
"Package source" must remember user feeds

### ISSUE THREAD

**Issue by RussKie** [maraf/GitExtensions.PluginManager#38]
Whenever the manager is launched a user must type package feeds over and over.

It would be great if "Package source" remembered all user feeds in a similar fashion VS remembers all NuGet feeds.
It would also be great if user could browse multiple feeds at the same time, e.g. "All" feeds.

**Comment by maraf** [comment]
Solved by 92f1068e7d0eb2469d0f08fa6cce3f9967587420.
