### ISSUE TITLE
Support multiple feeds

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#39]
Replace "Package Source" textbox with dropdown (accepting new items as user input).
Include option "All feeds".

Feeds could also be named as in VS.
![image](https://user-images.githubusercontent.com/10020471/46598143-53f8c780-cae3-11e8-9b61-52e0cb9a1e92.png)

TODO:
- [x] CRUD for package sources.
- [x] Remove `PackageSourceUrl` parameter from plugin.
- [x] Remove `PackageSourceUrl` parameter from manager.
- [x] UI for selecting active source.
- [x] Validate unique source name.
- [x] Apply selected source in BL.
- [x] Update CLI.

**Comment by RussKie** [comment]
May be something a bit more elaborate than a editable dropdown.

I don't entirely like the VS dialog but somewhat similar to:
![image](https://user-images.githubusercontent.com/4403806/46633798-844f6d00-cb9a-11e8-85a2-61e590b23d90.png)

Perhaps the 'cog' icon can open a new dialog that has just a textbox, that contains user feeds, one per line. Some logic maybe required to remove empty lines, a feed called 'All' etc.
This gives the user flexibility to add/edit/remove feeds easily, presents a simple UX, and make the implementation relatively straight forward.
From the user list the dropdown can be populated and, if there are feeds, 'All' feed is added to the head of the list.

**Comment by RussKie** [comment]
I'm looking from a very pragmatic reason - I don't think many GE users would ever change a defaults. So the out of the box experience must be as simple as possible.
It's impossible to tell how many of our users use VS, but NuGet is very much Microsoft/.NET thing, so if we give users a familiar looking dialog to manage feeds they would feel right at home. 
But we don't have to mimic the VS Nuget dialog, I personally find it not very usable.

**Comment by maraf** [comment]
OK. 
I'm going to implement feed selection as it's in VS.
"Paste and go" use-case might never be needed, we will see.

**Comment by maraf** [comment]
`NuGet.Client` has built-in support for managing sources.
Use class `PackageSourceProvider` and `ISettings`.

**Comment by maraf** [comment]
Ship next release with sources config file containing myget-ge.

**Comment by maraf** [comment]
![image](https://user-images.githubusercontent.com/10020471/46916186-61b4be00-cfb7-11e8-9911-32a35132261d.png)

**Comment by RussKie** [comment]
Nice
