### ISSUE TITLE
Install any version of package

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#49]
So those cases when user finds that latest version doesn't work and wants to try previous.

TODO:
- [x] NuGetInstallService.IsInstalled must check version.
- [x] Update to concrete version on Updates tab.
- [x] Remove Uninstall and Reinstall buttons from Browser tab.

**Comment by maraf** [comment]
Looking at some other plugin managers, it seems that most of them use "different view for different actions". Maybe the causes is the same I'm facing here - uninstall plugin has different context that the one present on Browser tab.
Right now I'm thinking of removing Uninstall and Reinstall from Browser tab.

**Comment by RussKie** [comment]
Could you perhaps provide some screenshots to other PMs?

**Comment by maraf** [comment]
Here are 4 states from VS extensions manager:
 - List of installed
 - Search results (installed and not-install extension is selected)
 - List of available updates

![image](https://user-images.githubusercontent.com/10020471/50091629-31cea480-020c-11e9-8fa6-9b3e9da030e9.png)

And here is the same from Notepad++:

![image](https://user-images.githubusercontent.com/10020471/50091981-22039000-020d-11e9-9d86-218aefbf3ee5.png)

**Comment by maraf** [comment]
The change is not dramatic. I'm only considering removal of Uninstall and Reinstall buttons from the browser tab (as PM doesn't have enough context for them).

When I get to PC I will post screens.

**Comment by maraf** [comment]
Comparison of Browser tab in v0.7.2 and current v0.8.0.

![packagemanager](https://user-images.githubusercontent.com/10020471/50140598-912cc300-02a5-11e9-910b-325341eb3b43.png)

**Comment by maraf** [comment]
Nah, update to concrete version is still missing.
