### ISSUE TITLE
Distribute GE PluginManager with default nuget.org package source

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#50]
Based on discussion at GitExtensions/GitExtensions#5775.
Original issue #39.

**Comment by maraf** [comment]
@Russkie 
PluginManager recognizes GE plugins by checking dependencies and looking for the [GitExtensions.Plugins](https://www.myget.org/feed/neptuo-gitextensions/package/nuget/GitExtensions.Plugins).

Are you ok (for a GE community) with me pushing this package to nuget.org?
Once it is there, it couldn't be changed, I would be the owner, etc.

One more idea: 
Currently this package is empty, but I was also considering that it could contain GE binaries and plugin could use those as compile time reference.

**Comment by maraf** [comment]
I'm marking this a as bug. 
We can't include NuGet.config in release/package as with every update, it would override user defined config.

When config file doesn't exist, NuGet automatically creates one and adds nuget.org source, so ideal.

**Comment by RussKie** [comment]
> PluginManager recognizes GE plugins by checking dependencies and looking for the [GitExtensions.Plugins](https://www.myget.org/feed/neptuo-gitextensions/package/nuget/GitExtensions.Plugins).

Could you please provide more context and the vision for this assembly/package - e.g. what it is, where the source is. versioning story etc.
Right now, my attention is stretched thin between RL commitments and the upcoming release, so I apologies for asking more questions that may typically require.
/cc: @spdr870 @gerhardol @drewnoakes 

> We can't include NuGet.config in release/package as with every update, it would override user defined config.

I don't think we should, but I'd like the plugin manager to have the primary feed entry set to nuget.org instead of myget.org when distributed with GE.

**Comment by RussKie** [comment]
It's late here, so my judgement is somewhat clouded right now, but I think
it would be more appropriate for GE to publish the meta package. Thinking
out loud, it probably should contain GitUIPluginInterfaces.dll.

**Comment by gerhardol** [comment]
> it would be more appropriate for GE to publish the meta package. Thinking out loud, it probably should contain GitUIPluginInterfaces.dll.

yes

The version dependency will be for the version of GitUIPluginInterfaces.dll as well as some other dlls: GitUI.dll, GitHub*.dll ICSharp, ConEmu as well some external dlls. I guess a few of them can be different in the main app vs the plugins, it will have to separated in GE too.

**Comment by RussKie** [comment]
Given that we are on a release runway and I am overwhelmed with RL commitments, I propose another option for consideration.

We bundle the PM into the upcoming release of GE, but we don't make any announcements about it. 
This way we can continue with the plugin management story. We will work through the API, the versioning and developer experience stories past the release.

Thoughts?

**Comment by maraf** [comment]
> The version dependency will be for the version of GitUIPluginInterfaces.dll as well as some other dlls: GitUI.dll, GitHub*.dll ICSharp, ConEmu as well some external dlls. I guess a few of them can be different in the main app vs the plugins, it will have to separated in GE too.

That's exactly the idea.

> We bundle the PM into the upcoming release of GE, but we don't make any announcements about it.
> This way we can continue with the plugin management story. We will work through the API, the versioning and developer experience stories past the release.

I'm ok with this. 
Maybe the dependency test can pass even when the GE.Plugins package doesn't exist in the feed. I'm going to try...

**Comment by maraf** [comment]
PluginManager now points to nuget.org by default.
I have published GitExtensions.PluginManager to nuget.org as well, so further updates can be done through this feed.

Regarding to GE.Plugins packages: Dependency check works even if this package isn't in the feed. It's kind a hacky, but for this (not-announced) release it's IMO ok.

**Comment by RussKie** [comment]
Awesome!
