### ISSUE TITLE
Submodule 

### ISSUE THREAD

**Issue by vbjay** [maraf/GitExtensions.PluginManager#56]
Should have made this a submodule project in Gitextensions repo and added it to the solution.  Storing binaries in the repo is going to bloat it as we change things.  You shouldn't include the references in the repo project.

**Comment by vbjay** [comment]
Here is the problem.  He has embedded our plugin assemblies in the git
repo. You don't include binaries in a repo if you can help it.   Instead of
this project being a submodule and adding a project reference to our
assemblies.  Auto update so when user is using an old version of GE and it
downloads a new gitextensions plugin library in the update and GE crashes
next time user runs GE because the plugin library is different than what GE
was compiled against, we do what?

**Comment by maraf** [comment]
There is much to do in the compatibility story. 
We have shared some thoughts in https://github.com/maraf/GitExtensions.PluginManager/issues/50.

Current mode "let me install everything" is kind a beta. There should be more strict solution where PM version is bound to a GE version range, but it requires to think through GE plugin-related binaries distribution etc.

**Comment by maraf** [comment]
I'm going to close this one as the discussion is not active.
Feel free to reopen it at any time.
