### ISSUE TITLE
"Downgrade" to .NET framework v4.6.1

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#57]

**Comment by sharwell** [comment]
📝 If you have references to dependencies that include .NET Standard builds, you may have trouble targeting .NET Framework 4.6.1. It's much safer to target .NET Framework 4.6 in this case.

**Comment by maraf** [comment]
Even when dependency is targets .NET Standard 2.0?

**Comment by sharwell** [comment]
*Especially* when the dependency targets .NET Standard 2.0. See https://github.com/github/VisualStudio/issues/1849 (the issue affects Visual Studio, but may be similar to what we saw in Git Extensions).

**Comment by maraf** [comment]
But when I set `<TargetFramework>net46</TargetFramework>`, build throws:

```
error NU1202: Package Neptuo 6.0.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package Neptuo 6.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
```

What am I missing?

**Comment by maraf** [comment]
Two more questions, please.
1) How can I get binaries if build fails? It's not a warning, it's an error which stops the build.
2) If I include `netstandard.dll` and other `System.*.dll` in PackageManger.exe (separate executable), will it work on Windows machine mentioned in GE comment above?
