### ISSUE TITLE
Install plugins to location provided by GitExtensions

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#59]
Use `%CommonApplicationData%\GitExtensions\plugins` for standard installation and current location only for portable GitExtensions.

Should PM be also there? If not, how should self-update work?

/cc @vbjay @Russkie

**Comment by RussKie** [comment]
> Use `%CommonApplicationData%\GitExtensions\plugins` for standard installation and current location only for portable GitExtensions.

I don't think it is the PM's concern. I think GE must expose a property that specifies the path to the Plugins directory for the current instance.

> how should self-update work?

Would the current mechanism not work?

**Comment by maraf** [comment]
> I don't think it is the PM's concern. I think GE must expose a property that specifies the path to the Plugins directory for the current instance.

You are absolutely right and this issue should only track changes to PM to use this property.

> Would the current mechanism not work?

Some plugins will remain in Program Files and only those installed through PM will be somewhere else, right? 
If so, PM must be in the "writable" location for current self-update to work. 
If all plugins goes to the writable location (even those distributed with GE), than my question is void.

**Comment by RussKie** [comment]
I would like to have all plugins eventually moved from the GE's
repo/installer and to be installed with the help of the PM.
We can update the installer to install plugins into another folder,
assuming we can update MEF to load from another writable location. In the
meantime, it possible, we can launch the PM as admin.
