### ISSUE TITLE
Notify other plugin authors about PluginManager

### ISSUE THREAD

**Issue by maraf** [maraf/GitExtensions.PluginManager#62]
Not now. One day.
Just to track found plugins.

- [ ] [volkanceylan/GitExtensions-SerenityFlow-Plugin](https://github.com/volkanceylan/GitExtensions-SerenityFlow-Plugin)
- [ ] [amcarthur/Zipper](https://github.com/amcarthur/Zipper)
- [ ] [EbenZhang/PReviewer](https://github.com/EbenZhang/PReviewer)
- [ ] [otmopo3/GitExtensionsOpenSolutionPlugin](https://github.com/otmopo3/GitExtensionsOpenSolutionPlugin)
- [ ] [andypaxo/ontime-git-extensions](https://github.com/andypaxo/ontime-git-extensions)
- [ ] [git-tfs/git-tfs-gitextensions-plugin](https://github.com/git-tfs/git-tfs-gitextensions-plugin)

**Comment by mast-eu** [comment]
I stumbled on https://github.com/git-tfs/git-tfs-gitextensions-plugin

And @SteveMcArthur expressed some general interest in a new plugin (gitextensions/gitextensions#5382)

**Comment by maraf** [comment]
Thanks! TFS seems quite dead, but I'm going to add it.

**Comment by maraf** [comment]
Closed by #81.
