### ISSUE TITLE
PluginManager fails, because of "No write access to C:\Program Files (x86)\GitExtensions\Plugins\NuGet.Config"

### ISSUE THREAD

**Issue by mast-eu** [maraf/GitExtensions.PluginManager#68]
I am not able to get GitExtensions.PluginManager to work on Win7 or Win10.

I downloaded v0.8.0 and copied GitExtensions.PluginManager.dll into C:\Program Files (x86)\GitExtensions\Plugins.  After starting GE, I see only the usual GE plugins in the Plugins menu.
Downgrading to GE 3.0.0 didn't help. I thought it might be a compatibility issue with GE versions newer than PluginManager, but that doesn't seem to be true.

The standalone version is running without issues.

## Environment
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 120dpi (125% scaling)

**Comment by maraf** [comment]
Version 0.8.0 works only with GE >= 3.0.0.

Couldn't the issue be related to UAC? Once I tested the downloaded release on a PC with UAC enabled, it behaved this way. The solution was to uncheck an option in GitExtensions.PluginManager.dll file properties which blocked execution of downloaded file.

![image](https://user-images.githubusercontent.com/10020471/55057567-d95c3e00-5069-11e9-9cd3-10d6cab54051.png)

If it's not the case, could you please try to build it from source? It may be as easy as cloning the source, opening the solution in VS, checking GitExtensions.PluginManager as startup project and hitting run.

AFAIK GitExtensions doesn't provide a log of plugin loading, so in release mode we are quite blind.

**Comment by mast-eu** [comment]
> uncheck an option in GitExtensions.PluginManager.dll file properties which blocked execution of downloaded file.

Yes, it helped. After unblocking, the PluginManager appeared in GE's Plugins menu.
However, it seems like there are further UAC related issues:
#### 1) No write access to `C:\Program Files (x86)\GitExtensions\Plugins\NuGet.Config`
This is the default path for GE, but write access is usually blocked by UAC. I got this error:
![error1](https://user-images.githubusercontent.com/46861028/55069542-99568480-5084-11e9-887f-d32f715c7606.png)
As workaround, I generated the file _NuGet.Config_ with the standalone application, indicating a path with write access: `PackageManager.UI.exe --path C:\proj`.
Then I manually copied the file _C:\proj\NuGet.Config_ to _C:\Program Files (x86)\GitExtensions\Plugins\NuGet.Config_. Note, I had to confirm UAC to be able to copy a file into _C:\Program Files (x86)\GitExtensions\Plugins_.

#### 2) UAC confirmation needed every time I click Plugins > PluginManager in GE
I get the UAC dialog asking "Do you want to allow PackageManager.UI.exe to run?" every time I use the PluginManager.
I do not want to disable UAC on my PC (and I don't think we can expect a normal user to do it as part of the installation routine). Therefore, in my opinion, the PluginManager should be able to run with UAC enabled, but without triggering any confirmation dialog.
For installation, it is acceptable to get a UAC confirmation dialog once.

**Comment by maraf** [comment]
1) I will check this. It seems that it tries to write to NuGet.config before checking elevated privileges.

2) This is definitely problem and the solution is to change plugin folder to point somewhere where user has rights to write.
This requires change both in GE and PM. PM issue is tracked here #59.
In the meantime, as PM is still in preview, UAC prompts everytime.
