### ISSUE TITLE
Differences using PluginManager as GE plugin and standalone application

### ISSUE THREAD

**Issue by mast-eu** [maraf/GitExtensions.PluginManager#69]
Comparing the GE plugin and the standalone application I noticed some differences that I cannot explain:

### Tab "Browse"

The GE plugin doesn't find anything:
![browse_plugin](https://user-images.githubusercontent.com/46861028/55076302-610b7200-5095-11e9-9bd0-69e4af8d4da6.png)

While the standalone application finds some packages:
![browse_standalone](https://user-images.githubusercontent.com/46861028/55076303-610b7200-5095-11e9-83e5-990ab129f19a.png)

BTW: What exactly does it search for? The search field is empty.

### Tab "Installed"
The GE plugin lists itself.
![installed_plugin](https://user-images.githubusercontent.com/46861028/55076304-610b7200-5095-11e9-99e6-085a933ac03e.png)

The standalone application lists nothing.

### Tab "Updates"
The GE plugin crashes:
![crash](https://user-images.githubusercontent.com/46861028/55076632-3cfc6080-5096-11e9-8bc7-2ec71cd50420.png)

The standalone application does not crash, but remains empty (I guess that's ok, since I do not have any plugins that might be updated).

**Comment by maraf** [comment]
There are differences in startup arguments for standalone and GE integrated instances.

### Browse
_GE_ - Filters only packages with dependency on `GitExtensions.Plugins` (which is a kind of meta package to mark packages as GE plugin). There is also a "bug" when using nuget.org (#67) as GE.Plugins is not yet pushed there and nuget.org requires dependencies to exist. So in GE mode with nuget.org nothing is found, but if you change the source to https://www.myget.org/F/neptuo-gitextensions/api/v2 plugins will appear.
_Standalone_ - As search box is empty, it shows a head of the nuget.org feed. No additional filters.

### Installed
_GE_ - Startup arguments contains a `--selfpackageid` to support self update. With this parameter PM is able to override itself when new version is available.

### Updates
Bug #70.

**Comment by RussKie** [comment]
This would be a great addition to the readme

**Comment by maraf** [comment]
@RussKie I'm going to integrate it.

**Comment by mast-eu** [comment]
Thank you for the explanations.

> _GE_ - Startup arguments contains a `--selfpackageid` to support self update. With this parameter PM is able to override itself when new version is available.

Is it the idea to keep the PluginManager as a plugin itself? 
Wouldn't it be more robust to have the PM tightly bundled to GE, probably even as part of GE's code so that everything gets compiled and installed together?

**Comment by maraf** [comment]
This may change in the future, but right now PM is designed as a plugin and also will be distributed as pre-installed plugin in the upcoming GE release.
As it is still in preview, it enables to update separately. 

We have discussed the option of integrating source code into the main GE repository and the long term vision is to separate plugins from the main repository and make them features to install.

PM may be different and one time it may the only pre-installed plugin. Than it may be the right choice to disable the self update. What's positive is that it will be a single-line change :-)

**Comment by maraf** [comment]
I'm going to close this one. If you have any further questions, feel free to reopen it.
